platform :ios, ‘8.0‘
target ‘IntelligentFactory’ do
use_frameworks! 
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.2'
pod 'FMDB', '~> 2.6.2'
pod 'WebViewJavascriptBridge', '~> 6.0.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'SSZipArchive', '~> 1.8.1'

end



